################################################################################
# This is the template for appveyor.yml which uses the "default model" of the
# test framework in https://github.com/PowerShell/DscResource.Tests.
#
# This template assumes you have connected your repository to AppVeyor
# (https://ci.appveyor.com).
#
# Before using it in your repository, modify places marked with 'TODO:'.
################################################################################

#---------------------------------#
#      environment configuration  #
#---------------------------------#

version: 1.0.{build}.0 # TODO: Modify version so it fits your versioning.

environment:
  gallery_api:
    secure: uwd5h4xufRG6/4wEOUIrdEeTkXYIiLFydKXhP5ZKv5j8rR2acKOHrsL7c2UoYmZQ

init:
  # Needed for publishing of examples, build worker defaults to core.autocrlf=input.
  - git config --global core.autocrlf true

install:
    - ps: |
        # This is workaround for AppVeyor replaces '.' with '-' in the folder name.
        Set-Location -Path 'C:\projects'
        Rename-Item -Path 'C:\projects\dscresource-template' -NewName 'DscResource.Template' -Force
        $env:APPVEYOR_BUILD_FOLDER = 'C:\projects\DscResource.Template'
        Set-Location -Path $env:APPVEYOR_BUILD_FOLDER
    - git clone https://github.com/PowerShell/DscResource.Tests
    - ps: Write-Verbose -Message "PowerShell version $($PSVersionTable.PSVersion)" -Verbose
    - ps: Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
    - ps: Invoke-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        # TODO:
        # To use -CodeCovIo parameter, the repository need to connected
        # to Codecov (see https://codecov.io/).
        Invoke-AppveyorTestScriptTask -CodeCoverage -CodeCovIo -ExcludeTag @()

# scripts to run before deployment.
after_test:
    - ps: |
        Write-Verbose -Message "Branch: $env:APPVEYOR_REPO_BRANCH" -Verbose
        Invoke-AppveyorAfterTestTask

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy_script:
  - ps: |
        Invoke-AppVeyorDeployTask
